name: Publish to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-lates
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Install all dependencies
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
        run: flutter pub get
      - name: Build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
        run: flutter build web --release --web-renderer html