name: Publish to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - name: Install all dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web --release --web-renderer html
      - name: Move assets
        run: mv build/web/assets/* build/web/ 
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: web-page
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
